added auto sync in syncronizer
francescopasin/ccybercoders pull request #273
Opened 2021-08-21 17:02 UTC by GianlucaGit

2021-08-22 14:51 UTC, francescopasin requested changes

2021-08-22 14:51 UTC, francescopasin commented on app/assets/sql/0_create_tables.sql
> +VALUES ('sync_time', '20.0');
in che unità di misura è?

2021-08-22 14:51 UTC, francescopasin commented on app/src/main.py
> +    container.wire(packages=[src, src.controller, src.model, src.view])
perché? non dovrebbe servire

2021-08-22 14:51 UTC, francescopasin commented on app/src/model/synchronizer/synchronizer.py
> +        if datetime.now().timestamp() - self.__last_sync_t > 2 or manual:
perché avete fatto così e non con il timer di cooldown come avevamo detto in call?

2021-08-22 14:51 UTC, francescopasin commented on app/src/router.py
> +        if not self.__watcher:
non va creato qua

2021-08-22 15:03 UTC, LorenzoMatt commented on app/assets/sql/0_create_tables.sql
> +VALUES ('sync_time', '20.0');
flaot

2021-08-22 15:04 UTC, LorenzoMatt commented on app/src/main.py
> +    container.wire(packages=[src, src.controller, src.model, src.view])
Serve per fare l'inject nella classe router

2021-08-22 15:05 UTC, LorenzoMatt commented on app/src/model/synchronizer/synchronizer.py
> +        if datetime.now().timestamp() - self.__last_sync_t > 2 or manual:
Perchè con un if ci sembrava più semplice

2021-08-22 16:18 UTC, francescopasin requested changes

2021-08-22 16:18 UTC, francescopasin commented on app/src/main.py
> +    container.wire(packages=[src, src.controller, src.model, src.view])
Appunto, che non va fatto

2021-08-22 16:18 UTC, francescopasin commented on app/src/router.py
> +        if not self.__watcher:
ribadisco

2021-08-22 16:30 UTC, francescopasin requested changes

2021-08-22 16:30 UTC, francescopasin commented on app/src/model/synchronizer/synchronizer.py
> +    __cooldown_timer: float
hai sbagliato il tipo

2021-08-22 16:30 UTC, francescopasin commented on app/src/model/synchronizer/synchronizer.py
> +    loop: asyncio.AbstractEventLoop
farla privata

2021-08-22 16:30 UTC, francescopasin commented on app/src/router.py
> +    def __init__(
riformattare giusto

2021-08-23 09:12 UTC, francescopasin requested changes

2021-08-23 09:12 UTC, francescopasin commented on app/src/model/synchronizer/synchronizer.py
> +    __is_cooldown = False
aggiungere tipo

2021-08-23 09:12 UTC, francescopasin commented on app/src/model/synchronizer/synchronizer.py
> +        self.__sync_time = 15.0  # float(self.__database_service.get_config('sync_time'))
prendere dal db

2021-08-23 09:12 UTC, francescopasin commented on app/src/model/synchronizer/synchronizer.py
> +        self.__cooldown_time = 5.0
prendere dal db (aggiungere valore di default nello script sql)

2021-08-23 09:33 UTC, francescopasin approved these changes

2021-08-23 09:34 UTC, merged